k9s:
  # Enable periodic refresh of resource browser windows. Default false
  liveViewAutoRefresh: true
  noExitOnCtrlC: false
  ui:
    enableMouse: true
    headless: false
    logoless: false
    crumbsless: false
    skin: transparent
  logger:
    tail: 200
    buffer: 500
    sinceSeconds: 300
    textWrap: true
    showTime: true
