k9s:
  liveViewAutoRefresh: true
  noExitOnCtrlC: true
  ui:
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: false
    skin: transparent
  logger:
    tail: 200
    buffer: 500
    sinceSeconds: 300
    textWrap: true
    showTime: true
