import = ["~/.config/alacritty/catppuccin_mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.85
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[keyboard]
bindings = [
  { key = "Left", mods = "Command", chars = "\u001B\u004F\u0048" },  # Skip line left
  { key = "Right", mods = "Command", chars = "\u001B\u004F\u0046" }, # Skip line right
  { key = "Left", mods = "Alt", chars = "\u001B\u0062" },            # Skip word left
  { key = "Right", mods = "Alt", chars = "\u001B\u0066" },           # Skip word right
  { key = "Back", mods = "Command", chars = "\u0015" },              # Delete line
  { key = "Back", mods = "Alt", chars = "\u001B\u007F" },            # Delete word
]
