k9s:
  cluster: aks-dsp-training-develop-southeastasia-001
  namespace:
    active: default
    lockFavorites: false
    favorites:
    - default
  view:
    active: context
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
